// <auto-generated />
namespace ChessMates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedbattr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedbattr));
        
        string IMigrationMetadata.Id
        {
            get { return "201901140406410_update-db-attr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
