// <auto-generated />
namespace ChessMates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sortplayercolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sortplayercolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201901092220591_sort-player-columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
